version: "3"

services:
  docker-mariaDB:
    container_name: docker-authDB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planit_auth
      MYSQL_USER: planit
      MYSQL_PASSWORD: planit1234
    ports:
      - 8000:3306

  docker-spring:
    container_name: docker-spring
    image: dlaudghtn/auth-service:v1
    restart: on-failure
    depends_on:
      - docker-mariaDB
    ports:
      - 9000:9000
