server:
  port: 9000

#security:
#  oauth2:
#    client:
#      client-id: auth_id
#      client-secret: auth_secret
#    resource:
#      jwt:
#        key-value: jwt_secret_key

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PLANIT_AUTHENFICATION?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      username: planit
      password: planit1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create
    showSql: true

