apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-auth-deployment
spec:
  selector:
    matchLabels:
      app: spring-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-auth
    spec:
      containers:
        - name: spring-auth
          image: shoon2430/auth-service:v1
          ports:
            - containerPort: 9000
